// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"zproject/user_service/biz/app"
	"zproject/user_service/biz/domain/repo"
	"zproject/user_service/biz/domain/service"
)

// Injectors from wire.go:

func InitUserAPP() *app.UserAPP {
	iUserDB := repo.NewIUserDB()
	userService := service.NewUserService(iUserDB)
	userAPP := app.NewUserAPP(userService)
	return userAPP
}
